function sum(obj) {
    const a = obj.a;
    const b = obj.b;
    return a + b;
}

let summed = sum({ a: 200, b: 100 });
/*
[generated bytecode for function:  (0x01e408211f4d <SharedFunctionInfo>)]
Bytecode length: 28
Parameter count 1
Register count 3
Frame size 24
OSR nesting level: 0
Bytecode Age: 0
         000001E40821203A @    0 : 12 00             LdaConstant [0]
         000001E40821203C @    2 : c5                Star1
         000001E40821203D @    3 : 27 fe f8          Mov <closure>, r2
         000001E408212040 @    6 : 62 43 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
         000001E408212045 @   11 : 13 01 00          LdaGlobal [1], [0]
         000001E408212048 @   14 : c5                Star1
         000001E408212049 @   15 : 7e 02 02 29       CreateObjectLiteral [2], [2], #41
         000001E40821204D @   19 : c4                Star2
         000001E40821204E @   20 : 5e f9 f8 03       CallUndefinedReceiver1 r1, r2, [3]
         000001E408212052 @   24 : 1d 02             StaCurrentContextSlot [2]
         000001E408212054 @   26 : 0d                LdaUndefined
         000001E408212055 @   27 : ab                Return
Constant pool (size = 3)
000001E408212005: [FixedArray] in OldSpace
 - map: 0x01e408042205 <Map>
 - length: 3
           0: 0x01e408211f9d <FixedArray[2]>
           1: 0x01e408211f09 <String[3]: #sum>
           2: 0x01e408211fe1 <ObjectBoilerplateDescription[5]>
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: sum (0x01e408211fad <SharedFunctionInfo sum>)]
Bytecode length: 16
Parameter count 2
Register count 2
Frame size 16
OSR nesting level: 0
Bytecode Age: 0
         000001E4082121B2 @    0 : 28 03 00 00       LdaNamedProperty a0, [0], [0]
         000001E4082121B6 @    4 : c6                Star0
         000001E4082121B7 @    5 : 28 03 01 02       LdaNamedProperty a0, [1], [2]
         000001E4082121BB @    9 : c5                Star1
         000001E4082121BC @   10 : 25 f9             Ldar r1
         000001E4082121BE @   12 : 35 fa 04          Add r0, [4]
         000001E4082121C1 @   15 : ab                Return
Constant pool (size = 2)
000001E408212181: [FixedArray] in OldSpace
 - map: 0x01e408042205 <Map>
 - length: 2
           0: 0x01e4080477bd <String[1]: #a>
           1: 0x01e408047859 <String[1]: #b>
Handler Table (size = 0)
Source Position Table (size = 0)
*/