function sum(obj) {
    return obj.a + obj.b;
}

let summed = sum({ a: 200, b: 100 });
/*
[generated bytecode for function:  (0x023308211f4d <SharedFunctionInfo>)]
Bytecode length: 28
Parameter count 1
Register count 3
Frame size 24
OSR nesting level: 0
Bytecode Age: 0
         000002330821203A @    0 : 12 00             LdaConstant [0]
         000002330821203C @    2 : c5                Star1
         000002330821203D @    3 : 27 fe f8          Mov <closure>, r2
         0000023308212040 @    6 : 62 43 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
         0000023308212045 @   11 : 13 01 00          LdaGlobal [1], [0]
         0000023308212048 @   14 : c5                Star1
         0000023308212049 @   15 : 7e 02 02 29       CreateObjectLiteral [2], [2], #41
         000002330821204D @   19 : c4                Star2
         000002330821204E @   20 : 5e f9 f8 03       CallUndefinedReceiver1 r1, r2, [3]
         0000023308212052 @   24 : 1d 02             StaCurrentContextSlot [2]
         0000023308212054 @   26 : 0d                LdaUndefined
         0000023308212055 @   27 : ab                Return
Constant pool (size = 3)
0000023308212005: [FixedArray] in OldSpace
 - map: 0x023308042205 <Map>
 - length: 3
           0: 0x023308211f9d <FixedArray[2]>
           1: 0x023308211f09 <String[3]: #sum>
           2: 0x023308211fe1 <ObjectBoilerplateDescription[5]>
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: sum (0x023308211fad <SharedFunctionInfo sum>)]
Bytecode length: 13
Parameter count 2
Register count 1
Frame size 8
OSR nesting level: 0
Bytecode Age: 0
         00000233082121B2 @    0 : 28 03 00 01       LdaNamedProperty a0, [0], [1]
         00000233082121B6 @    4 : c6                Star0
         00000233082121B7 @    5 : 28 03 01 03       LdaNamedProperty a0, [1], [3]
         00000233082121BB @    9 : 35 fa 00          Add r0, [0]
         00000233082121BE @   12 : ab                Return
Constant pool (size = 2)
0000023308212181: [FixedArray] in OldSpace
 - map: 0x023308042205 <Map>
 - length: 2
           0: 0x0233080477bd <String[1]: #a>
           1: 0x023308047859 <String[1]: #b>
Handler Table (size = 0)
Source Position Table (size = 0)
*/