let obj = { a: 200, b: 100 };
function sum(x, y) {
    return x + y;
}
const a = obj.a;
const b = obj.b;
let summed = sum(a, b);
/*
[generated bytecode for function:  (0x021808211f6d <SharedFunctionInfo>)]
Bytecode length: 54
Parameter count 1
Register count 4
Frame size 32
OSR nesting level: 0
Bytecode Age: 0
         000002180821207A @    0 : 12 00             LdaConstant [0]
         000002180821207C @    2 : c5                Star1
         000002180821207D @    3 : 27 fe f8          Mov <closure>, r2
         0000021808212080 @    6 : 62 43 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
         0000021808212085 @   11 : 7e 01 00 29       CreateObjectLiteral [1], [0], #41
         0000021808212089 @   15 : 1d 02             StaCurrentContextSlot [2]
         000002180821208B @   17 : 1a 02             LdaCurrentContextSlot [2]
         000002180821208D @   19 : c5                Star1
         000002180821208E @   20 : 28 f9 02 01       LdaNamedProperty r1, [2], [1]
         0000021808212092 @   24 : 1d 03             StaCurrentContextSlot [3]
         0000021808212094 @   26 : 1a 02             LdaCurrentContextSlot [2]
         0000021808212096 @   28 : c5                Star1
         0000021808212097 @   29 : 28 f9 03 03       LdaNamedProperty r1, [3], [3]
         000002180821209B @   33 : 1d 04             StaCurrentContextSlot [4]
         000002180821209D @   35 : 13 04 05          LdaGlobal [4], [5]
         00000218082120A0 @   38 : c5                Star1
         00000218082120A1 @   39 : 1b 03             LdaImmutableCurrentContextSlot [3]
         00000218082120A3 @   41 : c4                Star2
         00000218082120A4 @   42 : 1b 04             LdaImmutableCurrentContextSlot [4]
         00000218082120A6 @   44 : c3                Star3
         00000218082120A7 @   45 : 5f f9 f8 f7 07    CallUndefinedReceiver2 r1, r2, r3, [7]
         00000218082120AC @   50 : 1d 05             StaCurrentContextSlot [5]
         00000218082120AE @   52 : 0d                LdaUndefined
         00000218082120AF @   53 : ab                Return
Constant pool (size = 5)
000002180821203D: [FixedArray] in OldSpace
 - map: 0x021808042205 <Map>
 - length: 5
           0: 0x021808211fd5 <FixedArray[2]>
           1: 0x021808212019 <ObjectBoilerplateDescription[5]>
           2: 0x0218080477bd <String[1]: #a>
           3: 0x021808047859 <String[1]: #b>
           4: 0x021808211f19 <String[3]: #sum>
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: sum (0x021808211fe5 <SharedFunctionInfo sum>)]
Bytecode length: 6
Parameter count 3
Register count 0
Frame size 0
OSR nesting level: 0
Bytecode Age: 0
         000002180821220A @    0 : 25 04             Ldar a1
         000002180821220C @    2 : 35 03 00          Add a0, [0]
         000002180821220F @    5 : ab                Return
Constant pool (size = 0)
Handler Table (size = 0)
Source Position Table (size = 0)
*/