function incrementX(obj) {
    return 1 + obj.x;
}
  
incrementX({x: 42});
/* 
[generated bytecode for function:  (0x031008211f51 <SharedFunctionInfo>)]
Bytecode length: 26
Parameter count 1
Register count 3
Frame size 24
OSR nesting level: 0
Bytecode Age: 0
         000003100821202E @    0 : 12 00             LdaConstant [0]
         0000031008212030 @    2 : c5                Star1
         0000031008212031 @    3 : 27 fe f8          Mov <closure>, r2
         0000031008212034 @    6 : 62 43 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
         0000031008212039 @   11 : 13 01 00          LdaGlobal [1], [0]
         000003100821203C @   14 : c5                Star1
         000003100821203D @   15 : 7e 02 02 29       CreateObjectLiteral [2], [2], #41
         0000031008212041 @   19 : c4                Star2
         0000031008212042 @   20 : 5e f9 f8 03       CallUndefinedReceiver1 r1, r2, [3]
         0000031008212046 @   24 : c6                Star0
         0000031008212047 @   25 : ab                Return
Constant pool (size = 3)
0000031008211FF9: [FixedArray] in OldSpace
 - map: 0x031008042205 <Map>
 - length: 3
           0: 0x031008211f99 <FixedArray[2]>
           1: 0x031008211f09 <String[10]: #incrementX>
           2: 0x031008211fdd <ObjectBoilerplateDescription[3]>
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: incrementX (0x031008211fa9 <SharedFunctionInfo incrementX>)]
Bytecode length: 11
Parameter count 2
Register count 1
Frame size 8
OSR nesting level: 0
Bytecode Age: 0
         0000031008212166 @    0 : 0c 01             LdaSmi [1]
         0000031008212168 @    2 : c6                Star0
         0000031008212169 @    3 : 28 03 00 01       LdaNamedProperty a0, [0], [1]
         000003100821216D @    7 : 35 fa 00          Add r0, [0]
         0000031008212170 @   10 : ab                Return
Constant pool (size = 1)
0000031008212139: [FixedArray] in OldSpace
 - map: 0x031008042205 <Map>
 - length: 1
           0: 0x031008211f31 <String[1]: #x>
Handler Table (size = 0)
Source Position Table (size = 0)
*/