let obj = { a: 200, b: 100 };
function sum(x, y) {
    return x + y;
}
let summed = sum(obj.a, obj.b);
/*
[generated bytecode for function:  (0x00ec08211f6d <SharedFunctionInfo>)]
Bytecode length: 46
Parameter count 1
Register count 4
Frame size 32
OSR nesting level: 0
Bytecode Age: 0
         000000EC0821206A @    0 : 12 00             LdaConstant [0]
         000000EC0821206C @    2 : c5                Star1
         000000EC0821206D @    3 : 27 fe f8          Mov <closure>, r2
         000000EC08212070 @    6 : 62 43 01 f9 02    CallRuntime [DeclareGlobals], r1-r2
         000000EC08212075 @   11 : 7e 01 00 29       CreateObjectLiteral [1], [0], #41
         000000EC08212079 @   15 : 1d 02             StaCurrentContextSlot [2]
         000000EC0821207B @   17 : 13 02 01          LdaGlobal [2], [1]
         000000EC0821207E @   20 : c5                Star1
         000000EC0821207F @   21 : 1a 02             LdaCurrentContextSlot [2]
         000000EC08212081 @   23 : c4                Star2
         000000EC08212082 @   24 : 28 f8 03 03       LdaNamedProperty r2, [3], [3]
         000000EC08212086 @   28 : c4                Star2
         000000EC08212087 @   29 : 1a 02             LdaCurrentContextSlot [2]
         000000EC08212089 @   31 : c3                Star3
         000000EC0821208A @   32 : 28 f7 04 05       LdaNamedProperty r3, [4], [5]
         000000EC0821208E @   36 : c3                Star3
         000000EC0821208F @   37 : 5f f9 f8 f7 07    CallUndefinedReceiver2 r1, r2, r3, [7]
         000000EC08212094 @   42 : 1d 03             StaCurrentContextSlot [3]
         000000EC08212096 @   44 : 0d                LdaUndefined
         000000EC08212097 @   45 : ab                Return
Constant pool (size = 5)
000000EC0821202D: [FixedArray] in OldSpace
 - map: 0x00ec08042205 <Map>
 - length: 5
           0: 0x00ec08211fc5 <FixedArray[2]>
           1: 0x00ec08212009 <ObjectBoilerplateDescription[5]>
           2: 0x00ec08211f19 <String[3]: #sum>
           3: 0x00ec080477bd <String[1]: #a>
           4: 0x00ec08047859 <String[1]: #b>
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: sum (0x00ec08211fd5 <SharedFunctionInfo sum>)]
Bytecode length: 6
Parameter count 3
Register count 0
Frame size 0
OSR nesting level: 0
Bytecode Age: 0
         000000EC082121EA @    0 : 25 04             Ldar a1
         000000EC082121EC @    2 : 35 03 00          Add a0, [0]
         000000EC082121EF @    5 : ab                Return
Constant pool (size = 0)
Handler Table (size = 0)
Source Position Table (size = 0)
*/